### ISSUE TITLE
startup fails due to permission denied

### ISSUE THREAD

**Issue by nuaimat** [bpatterson971/docker-centos7-tomcat85#2]
Thank for your quick fix for the previous issue.
Now when I am trying to start the container, it exits directly. 
looking at docker logs:

/entrypoint.sh: line 2: /usr/local/apache-tomcat-8.5.20/bin/catalina.sh: Permission denied

**Comment by bpatterson971** [comment]
At some point, I configured the container to run as the user "nobody" which appears to have caused the issue.  I reverted that in the latest commit.  Go ahead and build again from the master branch and confirm it works.
